### ISSUE TITLE
StatTag fails with an uninformative error message when error occurs in sourced file

### ISSUE THREAD

**Issue by mronkko** [StatTag/StatTagMac#4]
I have two files, test.R and test2.R. test.R is linked in 

[https://github.com/StatTag/StatTagMac/issues/3](https://github.com/StatTag/StatTagMac/issues/3)

The content of test2.R is 

`source("test.R")

##>>>ST:Value(Label="test", Frequency="On Demand", Type="Numeric", Decimals=0, Thousands=False)
mean(d$a)
##<<<`

When I try to update a tag based on test2.R, I get the following error: 

"•  There was an error interpreting the expression.
(null)"

The reason for the error in test.R is an umlaut character, but this issue is not about that problem, but the problem that StatTag gives (null) instead of the actual problematic expression.

**Comment by lrasmus** [comment]
Thanks for reporting this as well!

**Comment by lrasmus** [comment]
Fixed in [RCocoa commit 7dc8ba67](https://github.com/StatTag/RCocoa/commit/7dc8ba67a177c44444d2de07c16161a3b9ee3a26)

**Comment by lrasmus** [comment]
Released in [StatTag for macOS v3.0.3](https://stattag-registration.fsm.northwestern.edu/)
